services:

  mysql:
    image: mysql:8.0
    container_name: projeto-crud-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: bd_produtos
      MYSQL_USER: coti
      MYSQL_PASSWORD: coti
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - projeto-crud-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: projeto-crud-phpmyadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: coti
      PMA_PASSWORD: coti
    depends_on:
      - mysql
    networks:
      - projeto-crud-network

networks:
  projeto-crud-network:
    driver: bridge

volumes:
  mysql_data: